services:
  backend:
    build:
      context: ./backend
    container_name: yoga-studio-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      API_PORT: 2005
    ports:
      - "2005:2005"
    volumes:
      - ./backend/storage:/app/storage

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: https://yogastudio-s.airepro.in/api/v1
    container_name: yoga-studio-ui
    restart: unless-stopped
    ports:
      - "2004:80"
    depends_on:
      - backend
